"""empty message

Revision ID: f1fa8292be9b
Revises: 
Create Date: 2020-11-03 12:09:15.129167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1fa8292be9b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # op.create_table('notebooks',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('title', sa.String(length=255), nullable=False),
    # sa.Column('isDefault', sa.Boolean(), nullable=False),
    # sa.Column('userId', sa.Integer(), nullable=False),
    # sa.Column('created_at', sa.DateTime(), nullable=False),
    # sa.Column('updated_at', sa.DateTime(), nullable=False),
    # sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    # sa.PrimaryKeyConstraint('id'),
    # sa.UniqueConstraint('title', 'userId')
    # )
    # op.create_table('tags',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('name', sa.String(length=20), nullable=False),
    # sa.Column('userId', sa.Integer(), nullable=False),
    # sa.Column('created_at', sa.DateTime(), nullable=False),
    # sa.Column('updated_at', sa.DateTime(), nullable=False),
    # sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    # sa.PrimaryKeyConstraint('id')
    # )
    # op.create_table('notes',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('title', sa.String(length=255), nullable=True),
    # sa.Column('content', sa.String(), nullable=False),
    # sa.Column('userId', sa.Integer(), nullable=False),
    # sa.Column('notebookId', sa.Integer(), nullable=True),
    # sa.Column('isTrash', sa.Boolean(), nullable=True),
    # sa.Column('created_at', sa.DateTime(), nullable=False),
    # sa.Column('updated_at', sa.DateTime(), nullable=False),
    # sa.ForeignKeyConstraint(['notebookId'], ['notebooks.id'], ),
    # sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    # sa.PrimaryKeyConstraint('id')
    # )
    # op.create_table('noteTags',
    # sa.Column('noteId', sa.Integer(), nullable=False),
    # sa.Column('tagId', sa.Integer(), nullable=False),
    # sa.ForeignKeyConstraint(['noteId'], ['notes.id'], ),
    # sa.ForeignKeyConstraint(['tagId'], ['tags.id'], ),
    # sa.PrimaryKeyConstraint('noteId', 'tagId')
    # )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('noteTags')
    # op.drop_table('notes')
    # op.drop_table('tags')
    # op.drop_table('notebooks')
    op.drop_table('users')
    # ### end Alembic commands ###
