"""create puzzles table

Revision ID: 4705a572c66b
Revises: f1fa8292be9b
Create Date: 2021-01-16 10:13:20.385241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4705a572c66b'
down_revision = 'f1fa8292be9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('packs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('totalPuzzles', sa.Integer(), nullable=False),
    sa.Column('isShared', sa.Boolean(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('puzzles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('difficulty', sa.String(), nullable=True),
    sa.Column('layout', sa.String(), nullable=False),
    sa.Column('solution', sa.String(), nullable=False),
    sa.Column('solutionMoves', sa.Integer(), nullable=False),
    sa.Column('totalStars', sa.Integer(), nullable=False),
    sa.Column('totalPlays', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('packId', sa.Integer(), nullable=True),
    sa.Column('isTrash', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['packId'], ['packs.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('puzzles')
    op.drop_table('packs')
    # ### end Alembic commands ###
